local M = {}

M.VERSION = 1

M.PLAYER_MIN = 2
M.PLAYER_MAX = 6

M.DICE_PER_PLAYER = 5
M.DICE_FACE_MIN = 1
M.DICE_FACE_MAX = 6
M.SKULL_FACE = 1

M.CYLINDER_SLOTS = 6
M.INITIAL_LOADED_SLOTS = { 1, 3, 5 }
M.INITIAL_HP = 6

M.BID_COUNT_MIN = 1
M.BID_COUNT_MAX = 36
M.DEFAULT_MMR = 1000
M.SHAKE_REQUIRED_ACTIONS = 6

M.BIDDING_OPEN_DELAY_MS = 3000
M.SHAKE_TIMEOUT_MS = 6000
M.DICE_CHECK_TIMEOUT_MS = 6000
M.BIDDING_TIMEOUT_MS = 40000
M.BID_RELOAD_TIMEOUT_MS = 3000
M.DUEL_REVEAL_INTERVAL_MS = 160
M.DUEL_REVEAL_DURATION_MS = 340
M.DUEL_REVEAL_HOLD_MS = 3000
M.DUEL_EXECUTE_INTRO_MS = 450
M.DUEL_ROULETTE_STEP_MS = 660
M.DUEL_PERFECT_STEP_MS = 1180
M.DUEL_COMPLETE_HOLD_MS = 1000

return M
